name: continuous

on: [push]

jobs:
    ubuntu-latest:
        name: ubuntu-latest
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/dotnet/sdk:5.0
        steps:
            - uses: actions/checkout@v1
            - name: Run './build.cmd'
              run: ./build.cmd
              env:
                  GitHubToken: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v1
