name: continuous

on: [push]

jobs:
    windows-latest:
        name: windows-latest
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run './build.cmd'
              run: ./build.cmd
              env:
                  GitHubToken: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v1
